# Generated by Django 2.1 on 2018-01-23 05:22

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='MsgData',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('send_name', models.CharField(max_length=20)),
                ('receive_name', models.CharField(max_length=20)),
                ('message', models.TextField()),
                ('send_time', models.CharField(max_length=20)),
            ],
        ),
    ]
